# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/data/webServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/data/webServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/data/webServer/CMakeFiles /root/data/webServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/data/webServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WebServer

# Build rule for target.
WebServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebServer
.PHONY : WebServer

# fast build rule for target.
WebServer/fast:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/build
.PHONY : WebServer/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/build
.PHONY : lib/fast

event/event.o: event/event.cpp.o

.PHONY : event/event.o

# target to build an object file
event/event.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/event.cpp.o
.PHONY : event/event.cpp.o

event/event.i: event/event.cpp.i

.PHONY : event/event.i

# target to preprocess a source file
event/event.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/event.cpp.i
.PHONY : event/event.cpp.i

event/event.s: event/event.cpp.s

.PHONY : event/event.s

# target to generate assembly for a file
event/event.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/event.cpp.s
.PHONY : event/event.cpp.s

event/looEvent.o: event/looEvent.cpp.o

.PHONY : event/looEvent.o

# target to build an object file
event/looEvent.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/looEvent.cpp.o
.PHONY : event/looEvent.cpp.o

event/looEvent.i: event/looEvent.cpp.i

.PHONY : event/looEvent.i

# target to preprocess a source file
event/looEvent.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/looEvent.cpp.i
.PHONY : event/looEvent.cpp.i

event/looEvent.s: event/looEvent.cpp.s

.PHONY : event/looEvent.s

# target to generate assembly for a file
event/looEvent.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/looEvent.cpp.s
.PHONY : event/looEvent.cpp.s

event/mytimer.o: event/mytimer.cpp.o

.PHONY : event/mytimer.o

# target to build an object file
event/mytimer.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/mytimer.cpp.o
.PHONY : event/mytimer.cpp.o

event/mytimer.i: event/mytimer.cpp.i

.PHONY : event/mytimer.i

# target to preprocess a source file
event/mytimer.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/mytimer.cpp.i
.PHONY : event/mytimer.cpp.i

event/mytimer.s: event/mytimer.cpp.s

.PHONY : event/mytimer.s

# target to generate assembly for a file
event/mytimer.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/event/mytimer.cpp.s
.PHONY : event/mytimer.cpp.s

httpUnit/HttpHandler.o: httpUnit/HttpHandler.cpp.o

.PHONY : httpUnit/HttpHandler.o

# target to build an object file
httpUnit/HttpHandler.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/HttpHandler.cpp.o
.PHONY : httpUnit/HttpHandler.cpp.o

httpUnit/HttpHandler.i: httpUnit/HttpHandler.cpp.i

.PHONY : httpUnit/HttpHandler.i

# target to preprocess a source file
httpUnit/HttpHandler.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/HttpHandler.cpp.i
.PHONY : httpUnit/HttpHandler.cpp.i

httpUnit/HttpHandler.s: httpUnit/HttpHandler.cpp.s

.PHONY : httpUnit/HttpHandler.s

# target to generate assembly for a file
httpUnit/HttpHandler.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/HttpHandler.cpp.s
.PHONY : httpUnit/HttpHandler.cpp.s

httpUnit/fast_cgi/fcgi.o: httpUnit/fast_cgi/fcgi.cpp.o

.PHONY : httpUnit/fast_cgi/fcgi.o

# target to build an object file
httpUnit/fast_cgi/fcgi.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/fcgi.cpp.o
.PHONY : httpUnit/fast_cgi/fcgi.cpp.o

httpUnit/fast_cgi/fcgi.i: httpUnit/fast_cgi/fcgi.cpp.i

.PHONY : httpUnit/fast_cgi/fcgi.i

# target to preprocess a source file
httpUnit/fast_cgi/fcgi.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/fcgi.cpp.i
.PHONY : httpUnit/fast_cgi/fcgi.cpp.i

httpUnit/fast_cgi/fcgi.s: httpUnit/fast_cgi/fcgi.cpp.s

.PHONY : httpUnit/fast_cgi/fcgi.s

# target to generate assembly for a file
httpUnit/fast_cgi/fcgi.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/fcgi.cpp.s
.PHONY : httpUnit/fast_cgi/fcgi.cpp.s

httpUnit/fast_cgi/tools.o: httpUnit/fast_cgi/tools.cpp.o

.PHONY : httpUnit/fast_cgi/tools.o

# target to build an object file
httpUnit/fast_cgi/tools.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/tools.cpp.o
.PHONY : httpUnit/fast_cgi/tools.cpp.o

httpUnit/fast_cgi/tools.i: httpUnit/fast_cgi/tools.cpp.i

.PHONY : httpUnit/fast_cgi/tools.i

# target to preprocess a source file
httpUnit/fast_cgi/tools.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/tools.cpp.i
.PHONY : httpUnit/fast_cgi/tools.cpp.i

httpUnit/fast_cgi/tools.s: httpUnit/fast_cgi/tools.cpp.s

.PHONY : httpUnit/fast_cgi/tools.s

# target to generate assembly for a file
httpUnit/fast_cgi/tools.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/fast_cgi/tools.cpp.s
.PHONY : httpUnit/fast_cgi/tools.cpp.s

httpUnit/httpparse.o: httpUnit/httpparse.cpp.o

.PHONY : httpUnit/httpparse.o

# target to build an object file
httpUnit/httpparse.cpp.o:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/httpparse.cpp.o
.PHONY : httpUnit/httpparse.cpp.o

httpUnit/httpparse.i: httpUnit/httpparse.cpp.i

.PHONY : httpUnit/httpparse.i

# target to preprocess a source file
httpUnit/httpparse.cpp.i:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/httpparse.cpp.i
.PHONY : httpUnit/httpparse.cpp.i

httpUnit/httpparse.s: httpUnit/httpparse.cpp.s

.PHONY : httpUnit/httpparse.s

# target to generate assembly for a file
httpUnit/httpparse.cpp.s:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/httpUnit/httpparse.cpp.s
.PHONY : httpUnit/httpparse.cpp.s

main/main.o: main/main.cpp.o

.PHONY : main/main.o

# target to build an object file
main/main.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/main/main.cpp.o
.PHONY : main/main.cpp.o

main/main.i: main/main.cpp.i

.PHONY : main/main.i

# target to preprocess a source file
main/main.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/main/main.cpp.i
.PHONY : main/main.cpp.i

main/main.s: main/main.cpp.s

.PHONY : main/main.s

# target to generate assembly for a file
main/main.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/main/main.cpp.s
.PHONY : main/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... WebServer"
	@echo "... rebuild_cache"
	@echo "... lib"
	@echo "... event/event.o"
	@echo "... event/event.i"
	@echo "... event/event.s"
	@echo "... event/looEvent.o"
	@echo "... event/looEvent.i"
	@echo "... event/looEvent.s"
	@echo "... event/mytimer.o"
	@echo "... event/mytimer.i"
	@echo "... event/mytimer.s"
	@echo "... httpUnit/HttpHandler.o"
	@echo "... httpUnit/HttpHandler.i"
	@echo "... httpUnit/HttpHandler.s"
	@echo "... httpUnit/fast_cgi/fcgi.o"
	@echo "... httpUnit/fast_cgi/fcgi.i"
	@echo "... httpUnit/fast_cgi/fcgi.s"
	@echo "... httpUnit/fast_cgi/tools.o"
	@echo "... httpUnit/fast_cgi/tools.i"
	@echo "... httpUnit/fast_cgi/tools.s"
	@echo "... httpUnit/httpparse.o"
	@echo "... httpUnit/httpparse.i"
	@echo "... httpUnit/httpparse.s"
	@echo "... main/main.o"
	@echo "... main/main.i"
	@echo "... main/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

